[project]
name = "iuttt"
version = "0.1.0"
description = "Infinite Ultimate Tic-Tac-Toe in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "build>=1.2.2.post1",
    "notebook>=7.4.4",
    "numpy>=2.3.1",
    "tabulate>=0.9.0",
]
