[project]
name = "ttt-py"
version = "0.1.0"
description = "Tic-Tac-Toe client in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "build>=1.2.2.post1",
    "notebook>=7.4.4",
    "numpy>=2.3.1",
]
